"""initial schema

Revision ID: 1e0a06814aae
Revises:
Create Date: 2026-06-29 19:07:36.056326

This migration is HAND-WRITTEN with raw ``op.execute`` SQL rather than
autogenerated. Alembic's autogenerate cannot reproduce three things this schema
relies on:

* the pgvector ``vector(768)`` column type (unknown to SQLAlchemy autogen),
* the generated ``content_tsv`` column (``GENERATED ALWAYS AS ... STORED``), and
* the HNSW / GIN index operator classes (``vector_cosine_ops``, GIN over tsvector).

The DDL below mirrors exactly what ``wise_mem.db.init_db()`` produces via
``SQLModel.metadata.create_all`` plus its two manual index creations, so the two
schema-creation paths are interchangeable.
"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e0a06814aae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the pgvector extension, the ``memory`` table, and its indexes."""
    # pgvector must exist before a table with a vector column can be created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # The `memory` table. Column order/types match SQLModel.metadata.create_all:
    #   - id: SERIAL primary key (auto-incrementing integer + owned sequence)
    #   - content/source: VARCHAR (SQLModel `str` maps to VARCHAR)
    #   - meta: JSONB NOT NULL DEFAULT '{}'
    #   - embedding: pgvector vector(768), nullable
    #   - created_at: timestamptz DEFAULT now()
    #   - content_tsv: generated, stored tsvector of content for full-text search
    op.execute(
        """
        CREATE TABLE memory (
            content VARCHAR NOT NULL,
            source VARCHAR,
            id SERIAL NOT NULL,
            meta JSONB DEFAULT '{}' NOT NULL,
            embedding VECTOR(768),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            content_tsv TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,
            PRIMARY KEY (id)
        )
        """
    )

    # HNSW index for fast approximate nearest-neighbour search by cosine distance.
    op.execute(
        "CREATE INDEX ix_memory_embedding "
        "ON memory USING hnsw (embedding vector_cosine_ops)"
    )

    # GIN index backing full-text search over the generated content_tsv column.
    op.execute("CREATE INDEX ix_memory_content_tsv ON memory USING gin (content_tsv)")


def downgrade() -> None:
    """Drop the ``memory`` table (and its indexes, which go with it)."""
    # Indexes are dropped implicitly with the table.
    op.execute("DROP TABLE IF EXISTS memory")
    # Leave the `vector` extension in place: other objects in the database may
    # depend on it, and dropping a shared extension on downgrade is surprising.
